### PR TITLE
Load all diffs on GitHub PRs

### PR DESCRIPTION
**Pull request by karlhorky**
Thanks so much for this userscript, amazing 🙌 

Quick PR to load all collapsed file diffs on GitHub PRs

Potential downside: PRs with lots of irrelevant diffs

### CODE REVIEW

**Comment by ivan** [comment]
Which page can I test this on?

**Comment by karlhorky** [comment]
Testing URL: any PR that has collapsed diffs.

Here's a smaller PR that it can be tested with:

- https://github.com/Shopify/web-configs/pull/157/files

**Comment by ivan** [comment]
OK, thanks. I've added your selector (though commented out) in https://github.com/ludios/expand-everything/commit/748a5b6e3fb39502551bdd40e60d41e63a6fbdf4 - it's not something I want by default because GitHub can already barely load some of these large diff pages, but also it's not obviously wrong, and people should just be able to just uncomment the selector if they want it. (I don't have configuration and I'm happy to see Expand Everything forked and modified as needed; it's hard to find the line between too little and too much expansion, e.g. the 'max mutations before stopping' values.)

**Comment by karlhorky** [comment]
Sounds good, thanks for the consideration and adding the commented-out rule!

**Pull request closed without merging**
